/**
 * Centralized Slovak UI copy. Keep all user-facing strings here.
 * Praise effort, not outcome ("Bravo, urobil si to!" not "Si super!").
 */
export const sk = {
  app: {
    title: "Domáce úlohy",
    description: "Aplikácia pre rodinu — splň úlohy, získaj čas na obrazovke.",
  },
  home: {
    tagline: "Vyber si, kto si",
    adminCta: "Rodič — prihlásiť sa",
    pickKid: "Vyber si svoj profil",
  },
  admin: {
    title: "Správa",
    loginTitle: "Prihlásenie rodiča",
    firstRunTitle: "Prvé spustenie — nastav heslo",
    firstRunHelp: "Žiadne heslo zatiaľ nie je nastavené. Heslo, ktoré teraz zadáš, bude tvoje admin heslo.",
    passwordLabel: "Heslo",
    loginButton: "Prihlásiť sa",
    setupButton: "Nastaviť heslo a prihlásiť",
    logout: "Odhlásiť sa",
    wrongPassword: "Nesprávne heslo. Skús to znova.",
    nav: {
      today: "Dnes",
      kids: "Deti",
      chores: "Úlohy",
      log: "Zaznamenať",
      calendar: "Kalendár",
      settings: "Nastavenia",
    },
    kids: {
      heading: "Deti",
      add: "Pridať dieťa",
      edit: "Upraviť",
      delete: "Vymazať",
      confirmDelete: "Naozaj vymazať toto dieťa? Záznamy sa zachovajú.",
      empty: "Zatiaľ tu nie sú žiadne deti. Pridaj prvé.",
      nameLabel: "Meno",
      emojiLabel: "Avatar (emoji)",
      colorLabel: "Farba",
      activeLabel: "Aktívne",
      save: "Uložiť",
      cancel: "Zrušiť",
    },
    chores: {
      heading: "Úlohy",
      add: "Pridať úlohu",
      edit: "Upraviť",
      delete: "Vymazať",
      confirmDelete: "Naozaj vymazať túto úlohu? Existujúce záznamy sa zachovajú.",
      empty: "Zatiaľ tu nie sú žiadne úlohy.",
      nameLabel: "Názov",
      iconLabel: "Ikonka",
      typeLabel: "Typ",
      rewardLabel: "Odmena (min)",
      bonusMinLabel: "Bonus min",
      bonusMaxLabel: "Bonus max",
      maxPerDayLabel: "Max za deň",
      maxPerWeekLabel: "Max za týždeň",
      activeLabel: "Aktívna",
      save: "Uložiť",
      cancel: "Zrušiť",
      groupHeading: {
        family_duty: "Rodinné povinnosti",
        earning_daily: "Denné úlohy",
        earning_weekly_quest: "Týždenné výzvy",
      },
    },
    log: {
      heading: "Zaznamenať",
      pickKid: "Pre koho?",
      completedChore: "Splnil úlohu",
      logScreenTime: "Použil obrazovku",
      adjustBalance: "Manuálna úprava",
      minutes: "Minúty",
      reason: "Dôvod",
      reasonPlaceholder: "(voliteľné)",
      log: "Zaznamenať",
      todayEntries: "Dnešné záznamy",
      noTodayEntries: "Dnes ešte nič nie je zaznamenané.",
      limitReached: "Limit pre túto úlohu dnes dosiahnutý.",
      weekLimitReached: "Týždenný limit pre túto úlohu dosiahnutý.",
      logged: "Zaznamenané ✓",
      awarded: "+{n} min",
      used: "−{n} min",
      adjusted: "úprava {n} min",
    },
    today: {
      heading: "Dnes",
      empty: "Zatiaľ dnes žiadne záznamy.",
      availableLabel: "Dnes k dispozícii",
      bankLabel: "V banke",
      usedTodayLabel: "Dnes minul",
      choresDoneLabel: "Splnené úlohy",
    },
    settings: {
      heading: "Nastavenia",
      familyName: "Názov rodiny",
      dailyCap: "Denný limit (min)",
      bankCap: "Limit banky (min)",
      defaultChoreMinutes: "Predvolené minúty za úlohu",
      save: "Uložiť",
      saved: "Uložené ✓",
      changePassword: "Zmeniť heslo",
      newPassword: "Nové heslo",
      passwordChanged: "Heslo zmenené ✓",
    },
  },
  chore: {
    type: {
      family_duty: "Rodinná povinnosť",
      earning_daily: "Denná úloha",
      earning_weekly_quest: "Týždenná výzva",
    },
    rewardMinutes: "minút za splnenie",
    done: "Hotovo!",
    praise: [
      "Bravo, urobil si to!",
      "Skvelá práca!",
      "Si šikovný!",
      "Výborne, pokračuj!",
    ],
  },
  kid: {
    todayLabel: "Dnes máš k dispozícii",
    bankLabel: "V banke",
    minutes: "minút",
    pickChore: "Vyber si úlohu",
    noChores: "Dnes už nie sú žiadne úlohy. Bav sa!",
  },
  calendar: {
    legend: {
      green: "Splnené",
      red: "Nesplnené alebo prečerpané",
      neutral: "Víkend / voľný deň",
    },
    months: [
      "Január", "Február", "Marec", "Apríl", "Máj", "Jún",
      "Júl", "August", "September", "Október", "November", "December",
    ],
    weekdaysShort: ["Po", "Ut", "St", "Št", "Pi", "So", "Ne"],
  },
  units: {
    min: "min",
  },
} as const;
